buildscript {
    repositories {
        //TODO! Del this!
        mavenLocal()

        mavenCentral()
    }

    dependencies {
        classpath 'info.gianlucacosta.aurora:aurora:10.0.0-SNAPSHOT'
    }
}


apply plugin: 'scala'
apply plugin: 'maven'
apply plugin: 'osgi'
apply plugin: 'info.gianlucacosta.aurora'


group = 'info.gianlucacosta.helios'
archivesBaseName = 'helios-core'
version = '7.0-SNAPSHOT'

description = 'Scala library of shared utilities'


dependencies {
    compile 'org.scala-lang:scala-library:2.11.8'
}


aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }
}
